
project = "LUX"

description = [[
Lua Utility eXTension is a Lua-only library compatible with Lua 5.1 through
Lua 5.3. It provides a number of features that one might need in everyday Lua
programming but cannot find in the standard library of the language.
]]

file = "lib"
dir = "doc/html"
pretty = "lxsh"
style = "doc"
template = "doc"
merge = true

examples = "examples"
format = "discount"

new_type("prototype", "Prototypes", true)

